name: Android CI
on:
  push:
    paths:
    - '*.gradle'
    - '*.properties'
    - app/*
  pull_request:
    paths:
    - '*.gradle'
    - '*.properties'
    - app/*

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create dummy keystore.properties
      run: echo "storeFile=keyStore.jks" > keystore.properties
    - name: Build with Gradle
      run: ./gradlew assembleDebug testDebug -x crashlyticsUploadDeobsDebug
